// Event constants
export const SOCKET_EVENTS = {
	USER_CONNECTED: "user has connected",
	USER_DISCONNECTED: "user has disconnected",
	USERNAME_ASSIGNED: "username assigned",
	CHANGE_NAME: "change name",
	SEND_MESSAGE: "send message",
	RECEIVE_MESSAGE: "receive message",
	CHANGE_ROOM_STATUS: "change room status",
	AFTER_CHANGE_ROOM_STATUS: "after change room status",
	SEND_POSITION: "send position",
	RECEIVE_POSITION: "receive position",
	RESOLVE_CHEST: "resolve chest",
	UPGRADE_PROPERTY: "upgrade property",
	PROPERTY_UPGRADED: "property upgraded",
	SEND_MONEY: "send money",
	SEND_TURN: "send turn",
	COLLECT_TAX: "collect tax",
	GO_TO_JAIL: "go to jail",
	JAIL_STATUS_CHANGED: "jail status changed",
	ACTIVATE_JAIL_CARD: "activate-jail-card",
	JAIL_CARD_ACTIVATED: "jail-card-activated",
	RECEIVE_TURN: "receive turn",
	SEND_VOTE: "send vote",
	RECEIVE_VOTE: "receive vote",
	RECEIVE_MONEY: "receive money",
	RECEIVE_MONEY_UPDATE: "receive money update",
	SEND_TRADE_OFFER: "send trade offer",
	RECEIVE_TRADE_OFFER: "receive trade offer",
	CONFIRM_TRADE_OFFER: "confirm trade offer",
	RECEIVE_CONFIRM_TRADE_OFFER: "receive confirm trade offer",
	BUY_PROPERTY: "buy property",
	PROPERTY_BOUGHT: "property bought",
	SEND_DICE_ROLL: "send dice roll",
	GET_DICE_ROLL: "get dice roll",
	CREATE_ROOM: "create room",
	GET_ALL_ROOMS: "get all rooms",
	JOIN_ROOM: "join room",
	JOIN_RANDOM_ROOM: "join random room",
	PLAYER_JOINED: "player joined",
	PLAYER_LEFT: "player left",
	GAME_LOOP: "game loop",
	REMOVE_PLAYER: "remove player",
	LEAVE_ROOM: "leave room",
	LEAVE_GAME: "leave game",
	CHAT_HISTORY: "chat history",
	ERROR: "error",
	YOUR_VOTES: "your votes",
	TIMER_TICK: "timer tick",
	TIMER_EXPIRED: "timer expired",
	ROOM_AUTO_DELETED: "room auto deleted",
	INACTIVITY_WARNING: "inactivity warning",
	INACTIVITY_TICK: "inactivity tick",
	CONFIRM_ACTIVITY: "confirm activity",
	INACTIVITY_RESET: "inactivity reset",
	GAME_FINISHED: "game finished",
	SELL_PROPERTY: "sell property",
	PROPERTY_SOLD: "property sold",
	START_AUCTION: "start auction",
	AUCTION_STARTED: "auction started",
	PLACE_BID: "place bid",
	AUCTION_UPDATED: "auction updated",
	AUCTION_ENDED: "auction ended",
} as const;
